### ISSUE TITLE
update_match_handicap有个bug

### ISSUE THREAD

**Issue by Grant6899** [xghgzxfp/bet_web#24]
https://github.com/xghgzxfp/bet_web/blob/ed153ac313fde45ef1da6a5d631b53a8371b86c3/worldcup/model.py#L294-L299

update盘口的时候只update了handicap 但是没有update handicap_display @ushuz

**Comment by Grant6899** [comment]
Fixed

**Comment by ushuz** [comment]
这个不需要你手关，等我那个 commit 合进 master 的时候自动会关掉
