### ISSUE TITLE
增加对多个赛事的支持

### ISSUE THREAD

**Issue by Grant6899** [xghgzxfp/bet_web#26]
目前想到的：

- [x] 前端增加drop down menu用于选择所显示的联赛，默认应为最新的比赛
- [x] 投注前需验证当前选手是否注册了当前联赛

**Comment by Grant6899** [comment]
@ushuz 对gamlber的数据结构，上面的哪个更合适？或者你有什么更好的想法？

**Comment by ushuz** [comment]
@Grant6899 

没法简单靠字段来区分，目前 `LEAGUE_NAME` 是和爬虫共用并对应澳盘网站的，网站上用的是“世界杯”而不是“2018世界杯”；如果要继续用字段来区分，需要改不少代码，且要洗这次世界杯的数据

我觉得用不同的数据库更方便一点，把 database 命名成 `worldcup-2018` 之类的，切换的时候直接切 database，国友赛数据已经放在一个叫 `international-friendlies` 的 database 里了

**Comment by Grant6899** [comment]
@ushuz 

爬虫的问题可以改一下match insert的逻辑， 加一个generate_cup的函数 合并联赛和年份。

我们这个数据结构这么相似 用不同数据库总感觉怪怪的

**Comment by ushuz** [comment]
@Grant6899 我们这种量级，不用考虑效率问题，也不会有啥效率问题，就是实例化一个新 `db` 的事情

**Comment by Grant6899** [comment]
I still prefer the second method I proposed:

每个联赛的参与名单单作为一个记录，把选手做成其下的数组

{
   league : "硬糙2018"
   gamblers: [
                           { name : "XX", openid : "XXXX"}
                           { name : "XX", openid : "XXXX"}
                            ............
                     ]
}

@Anserw  need a third person to make decision...

**Comment by Grant6899** [comment]
db structure:

'db' - 'collections'
logins - gambler
eurocup2016 - auction, match
worldcup2018 - auction, match

- update gambler中, rename后需要在model中遍历所有cup的db 逐条修改gambler 这里需要创建新的db指针

- required gambler不再从db里提取 而是存一个dict在config里 每次从那里拉不同赛事的参与者进行计算 这导致除了g.me以外 需要存一个g.cup(str). 那么model里增删改时，还是会由这个str出发建立新的db指针

所以我们需要在model.py里： from pymongo import MongoClient 

@ushuz 
评价一下这么做合适不合适

**Comment by ushuz** [comment]
@Grant6899 

工作量很不饱和呀朋友。

不必在 model.py 里引入 MongoClient，在 app.py 里做些改动即可：

```
db = app.db = MongoClient(app.config['MONGO_URI'])[app.config['MONGO_DBNAME']]
```
⬇️
```
dbclient = app.dbclient = MongoClient(app.config['MONGO_URI'])

def get_db(dbname=None):
    dbname = dbname or g.dbname or MONGO_DBNAME
    return dbclient[dbname]

db = LocalProxy(get_db)

@app.before_request
def before_request():
    g.dbname = xxxx or MONGO_DBNAME
```

用户在访问的时候在全局 contex `flask.g` 记录下现在应该用的 `dbname`，写一个 `get_db()` 这样 `dbclient[dbname]` 取到对应的 db 对象，可以通过 [LocalProxy](http://flask.pocoo.org/docs/1.0/appcontext/#storing-data) 把 get_db() 包装成 db 对象，这样 model 几乎不怎么需要改

**Comment by Grant6899** [comment]
https://github.com/xghgzxfp/bet_web/blob/3fa67fead3da8f2e1eddfc161738acab8fb0b90f/worldcup/model.py#L9

@ushuz 
这个tournamentdb的import有问题, 你之前是这个意思么？

**Comment by Grant6899** [comment]
https://github.com/xghgzxfp/bet_web/blob/4432782b648a09cdf896496539ca308c6627eb2c/worldcup/app.py#L17-L25

@ushuz 
你给的这几行我写的顺序好像还是有问题，会报一个这样的错:
RuntimeError: Working outside of application context.

**Comment by ushuz** [comment]
@Grant6899 看下这个 http://flask.pocoo.org/docs/1.0/appcontext/#manually-push-a-context

**Comment by Grant6899** [comment]
@ushuz 
match_getter 准备从哪儿获得db指针？

**Comment by Grant6899** [comment]
@ushuz 
我把LocalProxy去掉了，还是不太理解为啥需要这个

**Comment by Grant6899** [comment]
还有就是dict key顺序这个， 你是不是要更新到3.7

**Comment by ushuz** [comment]
> @ushuz
> 我把LocalProxy去掉了，还是不太理解为啥需要这个

少改代码

> 还有就是dict key顺序这个， 你是不是要更新到3.7

为啥需要 dict 有序？

**Comment by Grant6899** [comment]
扫尾工作:

- [ ] 服务器上添加login db
- [ ] 服务器上添加worldcup的备份worldcup2018
- [ ] worldcup2018 中的gambler应清空 并存储为以下结构

**Comment by Grant6899** [comment]
@ushuz 现在的版本merge之后是不是可以在服务器直接跑? 有没有什么遗漏的地方
