### ISSUE TITLE
投注后网页位置

### ISSUE THREAD

**Issue by Grant6899** [xghgzxfp/bet_web#8]
现在投注操作后会直接回到页面顶部，能否改成投注后位置不变？

**Comment by ushuz** [comment]
这个你搞了么？

**Comment by Grant6899** [comment]
没。 我们现在的显示都是从后端直接读的， 所以如果想实现这个功能的话可能需要在session 里存一下点投注按钮时的滚动条位置， 然后redirect后用js把位置变到存的位置上（我的猜想。。）

**Comment by ushuz** [comment]
@Grant6899 那样体验还是会很糟，用户是能看到 js 做的 scroll 的，跟跳一下没差。这个得用 js 发请求，根据服务器返回值更新 ui

**Comment by Grant6899** [comment]
@ushuz 我感觉你的意思是几乎整个html都用js生成了。。。

**Comment by ushuz** [comment]
@Grant6899 这就是前端界的趋势，React / Vue 了解一下

**Comment by Grant6899** [comment]
@ushuz 你这“了解一下”说的容易，一了解就是一晚上。。。

**Comment by ushuz** [comment]
@Grant6899 但我们的场景不需要 React / Vue 那么复杂了，ajax 是 gmail 从 2004 年就开始用的技术，也只需要用 js 改投注者那两个列表而已

**Comment by Grant6899** [comment]
通过“把最新的比赛置于顶部”修复
